import { SITE_URL } from "./site-url";

/** The share image generated by src/app/og.png/route.tsx, as an absolute URL. */
export const OG_IMAGE = {
  url: `${SITE_URL}/og.png`,
  width: 1200,
  height: 630,
  alt: "Ruth Ramos — Full Stack Developer, Madrid",
};
