// Generates the dotted-continent points for the home globe (src/components/world/land-points.ts).
// Evenly spaced points on a sphere (Fibonacci lattice), kept where they fall on land.
// Usage: pnpm globe-points
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoContains } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const topo = JSON.parse(readFileSync(require.resolve("world-atlas/land-110m.json"), "utf8"));
const land = feature(topo, topo.objects.land);

const SAMPLES = 16000;
const golden = Math.PI * (3 - Math.sqrt(5));
const points = [];
for (let i = 0; i < SAMPLES; i++) {
  const y = 1 - (i / (SAMPLES - 1)) * 2;
  const lat = (Math.asin(y) * 180) / Math.PI;
  const lon = ((((i * golden * 180) / Math.PI) % 360) + 540) % 360 - 180;
  if (lat < -60) continue; // skip Antarctica
  if (geoContains(land, [lon, lat])) points.push(Math.round(lat * 10) / 10, Math.round(lon * 10) / 10);
}

writeFileSync(
  new URL("../src/components/world/land-points.ts", import.meta.url),
  `// Generated by scripts/globe-points.mjs — do not edit by hand.
// Flat [lat, lon, lat, lon, …] of evenly spaced points on land (Natural Earth 110m via world-atlas).
export const LAND_POINTS: readonly number[] = [${points.join(",")}];
`,
);
console.log(`wrote ${points.length / 2} land points`);
