// Generates the mirrored-RR monogram paths from Bodoni Moda (opsz 96).
// Two capital R's share one stem: the second is the first mirrored about x = 50.
// Usage: pnpm monogram
import { writeFileSync } from "node:fs";
import opentype from "opentype.js";

const FONT = new URL("../assets/fonts/BodoniModa-96-Regular.ttf", import.meta.url);
const OUT = new URL("../src/components/brand/monogram-paths.ts", import.meta.url);

const SIZE = 88; // glyph size in the 100×100 viewBox
const BASELINE = 82;
const STEM_OFFSET = -15.5; // pulls the stem onto the centre line so both R's share it

const font = opentype.loadSync(FONT.pathname);
const path = font.getPath("R", 50 + STEM_OFFSET, BASELINE, SIZE).toPathData(2);

writeFileSync(
  OUT,
  `// Generated by scripts/monogram.mjs — do not edit by hand.
export const MONOGRAM_PATH = "${path}";
export const MONOGRAM_MIRROR = "translate(100 0) scale(-1 1)";
`,
);
console.log(`wrote ${OUT.pathname} (${path.length} chars)`);
